version: '3'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: seria
                uid: 1000
        ports:
            - 8005:8000
        env_file:
            - .env
        command: >
            sh -c "php artisan serve --host=0.0.0.0"
        volumes:
            - '.:/var/www'
        networks:
            - sail
        depends_on:
            - db
            - mailpit
    db:
        image: 'postgres:15'
        environment:
            PGPASSWORD: root
            POSTGRES_DB: pml_db
            POSTGRES_USER: pml_user
            POSTGRES_PASSWORD: Pmylike@1
        volumes:
            - 'sail-pgsql:/var/lib/postgresql/data'
            - './docker/pgsql/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - pml_db
                - '-U'
                - pml_user
            retries: 3
            timeout: 5s
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
